name: app_1
description: A new Flutter project.
publish_to: 'none' # Remove or replace with a URL if publishing

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.0

  # UI Components
  flutter_svg: ^2.0.7
  flutter_credit_card: ^4.1.0
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # Carousel and Charts
  carousel_slider: ^5.0.0
  fl_chart: ^1.0.0

  # Networking & Images
  http: ^1.4.0
  dio: ^5.3.3
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.2

  # State Management
  provider: ^6.1.1
  flutter_bloc: ^9.1.1
  riverpod: ^2.4.9
  equatable: ^2.0.5

  # Navigation
  go_router: ^15.1.2

  # Data & Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Forms & Validation
  formz: ^0.8.0
  flutter_form_builder: ^10.0.1
  email_validator: ^3.0.0

  # Payments
  razorpay_flutter: ^1.3.1
  pay: ^3.2.1
  upi_payment_qrcode_generator: ^1.0.3

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.1.11
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/slide1.jpg
