name: app_1
description: A new Flutter project.
publish_to: 'none' # Remove or replace with a URL if publishing

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.0.15

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Charts for dashboard
  fl_chart: ^1.0.0

  # Networking & images
  http: ^1.4.0
  fluttertoast: ^8.2.2
  cached_network_image: ^3.3.1
  intl: ^0.20.2

  # Carousel slider
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/slide1.jpg
    - assets/
